#ifndef REGISTRY_ACTION_FLAGS_H
#define REGISTRY_ACTION_FLAGS_H
#pragma once

#define ACTIONFLAG_DEBUG_NOTIFY (1 << 0)
#define ACTIONFLAG_BLOCK (1 << 1)
#define ACTIONFLAG_SEND_NOTIFICATION_TO_QUEUE (1 << 2)

#endif // !REGISTRY_ACTION_FLAGS_H 
